# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f977251ba71c3a0956eac5fc642469f79c9dfc1636bd403f7131b225cd09f66c45bc50cbe7fc64f1b7804145c60ee35d8dc8e7077d199377ce22df0246b8e55

test:
  secret_key_base: 9d120a9a2b61fd0f75d6e05d66efd9bde7d559a4cd3efd045a1b54cc3c6c30f04ce60f5791f7d7cbe9e4b33dc0af068ab80b095c74d04e438bf5509ba47dd853

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
